/**
 * Auto-generated schema for creative_event
 * Generated by: node scripts/generate-schemas.js
 * Source: schemas/spark/creative_event.yaml
 *
 * DO NOT EDIT MANUALLY - regenerate with: make update-spark-schema
 */

const CREATIVE_EVENT_SCHEMA = {
  name: "creative_event",
  fields: [
    {
      "name": "raw_url",
      "type": "string"
    },
    {
      "name": "bidobjid",
      "type": "string"
    },
    {
      "name": "oid",
      "type": "string"
    },
    {
      "name": "cid",
      "type": "string"
    },
    {
      "name": "crpid",
      "type": "string"
    },
    {
      "name": "time",
      "type": "integer"
    },
    {
      "name": "timestamp_ms",
      "type": "long"
    },
    {
      "name": "client_timestamp_ms",
      "type": "long"
    },
    {
      "name": "show_id",
      "type": "string"
    },
    {
      "name": "event_type",
      "type": "string"
    },
    {
      "name": "w",
      "type": "integer"
    },
    {
      "name": "h",
      "type": "integer"
    },
    {
      "name": "state",
      "type": "string"
    },
    {
      "name": "points",
      "type": "string"
    },
    {
      "name": "cr_pos",
      "type": "string"
    },
    {
      "name": "clkloc",
      "type": "string"
    },
    {
      "name": "element",
      "type": "string"
    },
    {
      "name": "current_scene",
      "type": "string"
    },
    {
      "name": "next_scene",
      "type": "string"
    },
    {
      "name": "action",
      "type": "string"
    },
    {
      "name": "bidder_click_handler_version",
      "type": "integer"
    },
    {
      "name": "actual_click_handler_version",
      "type": "integer"
    },
    {
      "name": "play_video",
      "type": "string"
    },
    {
      "name": "details",
      "type": "string"
    },
    {
      "name": "_dt",
      "type": "string"
    }
  ]
};
