/**
 * Auto-generated schema for creative_perf_event
 * Generated by: node scripts/generate-schemas.js
 * Source: schemas/spark/creative_perf_event.yaml
 *
 * DO NOT EDIT MANUALLY - regenerate with: make update-spark-schema
 */

const CREATIVE_PERF_EVENT_SCHEMA = {
  name: "creative_perf_event",
  fields: [
    {
      "name": "bidobjid",
      "type": "string"
    },
    {
      "name": "show_id",
      "type": "string"
    },
    {
      "name": "type",
      "type": "string"
    },
    {
      "name": "value",
      "type": "string"
    },
    {
      "name": "details",
      "type": "string"
    },
    {
      "name": "time",
      "type": "long"
    },
    {
      "name": "timestamp_ms",
      "type": "long"
    },
    {
      "name": "_dt",
      "type": "string"
    }
  ]
};
