/**
 * Auto-generated schema for imp_join_all2
 * Generated by: node scripts/generate-schemas.js
 * Source: schemas/spark/imp_join_all2.yaml
 *
 * DO NOT EDIT MANUALLY - regenerate with: make update-spark-schema
 */

const IMP_JOIN_ALL2_SCHEMA = {
  name: "imp_join_all2",
  fields: [
    {
      "name": "impreq_time",
      "type": "integer"
    },
    {
      "name": "win_time",
      "type": "integer"
    },
    {
      "name": "show_time",
      "type": "integer"
    },
    {
      "name": "click_time",
      "type": "integer"
    },
    {
      "name": "action_time",
      "type": "integer"
    },
    {
      "name": "req_id",
      "type": "binary"
    },
    {
      "name": "partner_id",
      "type": "integer"
    },
    {
      "name": "age",
      "type": "integer"
    },
    {
      "name": "current_age",
      "type": "integer"
    },
    {
      "name": "gender",
      "type": "integer"
    },
    {
      "name": "appier_cookie_uid",
      "type": "binary"
    },
    {
      "name": "googleuid",
      "type": "binary"
    },
    {
      "name": "app_id",
      "type": "binary"
    },
    {
      "name": "app_pub",
      "type": "binary"
    },
    {
      "name": "bundle_id",
      "type": "binary"
    },
    {
      "name": "app_type",
      "type": "integer"
    },
    {
      "name": "categories",
      "type": "array<integer>",
      "isArrayPrimitive": true,
      "elementType": "integer"
    },
    {
      "name": "page",
      "type": "binary"
    },
    {
      "name": "web_host",
      "type": "binary"
    },
    {
      "name": "browser",
      "type": "integer"
    },
    {
      "name": "browser_version",
      "type": "binary"
    },
    {
      "name": "isp",
      "type": "integer"
    },
    {
      "name": "device_type",
      "type": "integer"
    },
    {
      "name": "dnt",
      "type": "boolean"
    },
    {
      "name": "country",
      "type": "integer"
    },
    {
      "name": "lat",
      "type": "double"
    },
    {
      "name": "lon",
      "type": "double"
    },
    {
      "name": "os",
      "type": "integer"
    },
    {
      "name": "timezone",
      "type": "integer"
    },
    {
      "name": "zip",
      "type": "binary"
    },
    {
      "name": "lang",
      "type": "array<integer>",
      "isArrayPrimitive": true,
      "elementType": "integer"
    },
    {
      "name": "pf_appier",
      "type": "double"
    },
    {
      "name": "currency",
      "type": "integer"
    },
    {
      "name": "imp_position",
      "type": "integer"
    },
    {
      "name": "imp_width",
      "type": "integer"
    },
    {
      "name": "imp_height",
      "type": "integer"
    },
    {
      "name": "imp_type",
      "type": "integer"
    },
    {
      "name": "imp_maxbitrate",
      "type": "long"
    },
    {
      "name": "imp_maxduration",
      "type": "integer"
    },
    {
      "name": "imp_minbitrate",
      "type": "integer"
    },
    {
      "name": "imp_minduration",
      "type": "integer"
    },
    {
      "name": "imp_is_instl",
      "type": "boolean"
    },
    {
      "name": "imp_supported_api",
      "type": "array<integer>",
      "isArrayPrimitive": true,
      "elementType": "integer"
    },
    {
      "name": "bid_appier_id",
      "type": "binary"
    },
    {
      "name": "cid",
      "type": "string"
    },
    {
      "name": "crid",
      "type": "binary"
    },
    {
      "name": "crpid",
      "type": "string"
    },
    {
      "name": "bid_price_appier",
      "type": "double"
    },
    {
      "name": "win_price_appier",
      "type": "double"
    },
    {
      "name": "city_gnid",
      "type": "long"
    },
    {
      "name": "region_code",
      "type": "binary"
    },
    {
      "name": "ua_device_model",
      "type": "integer"
    },
    {
      "name": "connection_type",
      "type": "integer"
    },
    {
      "name": "tagid",
      "type": "binary"
    },
    {
      "name": "persona_gender",
      "type": "integer"
    },
    {
      "name": "persona_age_group",
      "type": "integer"
    },
    {
      "name": "win_ip",
      "type": "binary"
    },
    {
      "name": "show_ip",
      "type": "binary"
    },
    {
      "name": "click_ip",
      "type": "binary"
    },
    {
      "name": "is_external",
      "type": "boolean"
    },
    {
      "name": "net_cookie_uid",
      "type": "binary"
    },
    {
      "name": "viewability",
      "type": "integer"
    },
    {
      "name": "time",
      "type": "integer"
    },
    {
      "name": "appier_cookie_uidsha1",
      "type": "binary"
    },
    {
      "name": "dyngrp",
      "type": "binary"
    },
    {
      "name": "dynlnkg",
      "type": "binary"
    },
    {
      "name": "dyninfo",
      "type": "binary"
    },
    {
      "name": "deal_id",
      "type": "binary"
    },
    {
      "name": "bid_deal_id",
      "type": "string"
    },
    {
      "name": "bid_user_list",
      "type": "binary"
    },
    {
      "name": "bidding_alg",
      "type": "binary"
    },
    {
      "name": "click_through_rate",
      "type": "double"
    },
    {
      "name": "app_name",
      "type": "binary"
    },
    {
      "name": "experiment_features",
      "type": "binary"
    },
    {
      "name": "persona_age_source",
      "type": "integer"
    },
    {
      "name": "deals",
      "type": "array<binary>",
      "isArrayPrimitive": true,
      "elementType": "binary"
    },
    {
      "name": "bidding_alg_info",
      "type": "binary"
    },
    {
      "name": "is_rewarded",
      "type": "boolean"
    },
    {
      "name": "publisher_country",
      "type": "string"
    },
    {
      "name": "bidder",
      "type": "string"
    },
    {
      "name": "click_x_request_with",
      "type": "string"
    },
    {
      "name": "skippable",
      "type": "boolean"
    },
    {
      "name": "click_is_fraud",
      "type": "boolean"
    },
    {
      "name": "click_is_counted",
      "type": "boolean"
    },
    {
      "name": "bidding_gender",
      "type": "integer"
    },
    {
      "name": "bidding_age_group",
      "type": "integer"
    },
    {
      "name": "auction_type",
      "type": "integer"
    },
    {
      "name": "actions",
      "type": "array<struct>",
      "isArrayStruct": true,
      "elementFields": [
        {
          "name": "unique_user_id",
          "type": "string"
        },
        {
          "name": "action_id",
          "type": "string"
        },
        {
          "name": "purchase_currency",
          "type": "string"
        },
        {
          "name": "postback_time",
          "type": "integer"
        },
        {
          "name": "revenue_usd_appier",
          "type": "double"
        },
        {
          "name": "invalid_reason",
          "type": "string"
        },
        {
          "name": "x_invalid_reason",
          "type": "string"
        },
        {
          "name": "x_invalid_sub_reason",
          "type": "string"
        },
        {
          "name": "pub_id",
          "type": "string"
        },
        {
          "name": "subpub_id",
          "type": "string"
        },
        {
          "name": "appier_nonce",
          "type": "string"
        },
        {
          "name": "x_click_timestamp",
          "type": "long"
        },
        {
          "name": "x_impression_timestamp",
          "type": "long"
        },
        {
          "name": "x_install_timestamp",
          "type": "long"
        },
        {
          "name": "match_type",
          "type": "string"
        },
        {
          "name": "log_type",
          "type": "string"
        },
        {
          "name": "x_conversion_timestamp",
          "type": "long"
        },
        {
          "name": "scenario_type",
          "type": "string"
        }
      ]
    },
    {
      "name": "actions.unique_user_id",
      "type": "string"
    },
    {
      "name": "actions.action_id",
      "type": "string"
    },
    {
      "name": "actions.purchase_currency",
      "type": "string"
    },
    {
      "name": "actions.postback_time",
      "type": "integer"
    },
    {
      "name": "actions.revenue_usd_appier",
      "type": "double"
    },
    {
      "name": "actions.invalid_reason",
      "type": "string"
    },
    {
      "name": "actions.x_invalid_reason",
      "type": "string"
    },
    {
      "name": "actions.x_invalid_sub_reason",
      "type": "string"
    },
    {
      "name": "actions.pub_id",
      "type": "string"
    },
    {
      "name": "actions.subpub_id",
      "type": "string"
    },
    {
      "name": "actions.appier_nonce",
      "type": "string"
    },
    {
      "name": "actions.x_click_timestamp",
      "type": "long"
    },
    {
      "name": "actions.x_impression_timestamp",
      "type": "long"
    },
    {
      "name": "actions.x_install_timestamp",
      "type": "long"
    },
    {
      "name": "actions.match_type",
      "type": "string"
    },
    {
      "name": "actions.log_type",
      "type": "string"
    },
    {
      "name": "actions.x_conversion_timestamp",
      "type": "long"
    },
    {
      "name": "actions.scenario_type",
      "type": "string"
    },
    {
      "name": "impreq_country",
      "type": "string"
    },
    {
      "name": "click_country",
      "type": "string"
    },
    {
      "name": "click_ext_info.accept",
      "type": "string"
    },
    {
      "name": "click_ext_info.accept_lang",
      "type": "string"
    },
    {
      "name": "click_ext_info.bwdata",
      "type": "string"
    },
    {
      "name": "click_ext_info.idfa",
      "type": "string"
    },
    {
      "name": "click_ext_info.maxmind_asn",
      "type": "long"
    },
    {
      "name": "click_ext_info.maxmind_city",
      "type": "string"
    },
    {
      "name": "click_ext_info.maxmind_city_gnid",
      "type": "string"
    },
    {
      "name": "click_ext_info.maxmind_org",
      "type": "string"
    },
    {
      "name": "click_ext_info.ua_browser",
      "type": "string"
    },
    {
      "name": "click_ext_info.ua_device",
      "type": "string"
    },
    {
      "name": "click_ext_info.pub_id",
      "type": "string"
    },
    {
      "name": "click_ext_info.subpub_id",
      "type": "string"
    },
    {
      "name": "click_ext_info.os_version",
      "type": "string"
    },
    {
      "name": "click_ext_info.ip_is_anonymous",
      "type": "boolean"
    },
    {
      "name": "click_ext_info.ip_is_anonymous_vpn",
      "type": "boolean"
    },
    {
      "name": "click_ext_info.ip_is_hosting_provider",
      "type": "boolean"
    },
    {
      "name": "click_ext_info.ip_is_public_proxy",
      "type": "boolean"
    },
    {
      "name": "click_ext_info.ip_is_residential_proxy",
      "type": "boolean"
    },
    {
      "name": "click_ext_info.ip_is_tor_exit_node",
      "type": "boolean"
    },
    {
      "name": "win_country",
      "type": "string"
    },
    {
      "name": "show_country",
      "type": "string"
    },
    {
      "name": "impreq_rtb_info.appier_cookie_uid",
      "type": "string"
    },
    {
      "name": "impreq_rtb_info.googleuid",
      "type": "string"
    },
    {
      "name": "impreq_rtb_info.idfa",
      "type": "string"
    },
    {
      "name": "impreq_rtb_info.ua",
      "type": "string"
    },
    {
      "name": "impreq_rtb_info.os_version",
      "type": "string"
    },
    {
      "name": "impreq_rtb_info.idfv",
      "type": "string"
    },
    {
      "name": "impreq_rtb_info.ip_is_anonymous",
      "type": "boolean"
    },
    {
      "name": "impreq_rtb_info.ip_is_anonymous_vpn",
      "type": "boolean"
    },
    {
      "name": "impreq_rtb_info.ip_is_hosting_provider",
      "type": "boolean"
    },
    {
      "name": "impreq_rtb_info.ip_is_masked",
      "type": "boolean"
    },
    {
      "name": "impreq_rtb_info.ip_is_public_proxy",
      "type": "boolean"
    },
    {
      "name": "impreq_rtb_info.ip_is_residential_proxy",
      "type": "boolean"
    },
    {
      "name": "impreq_rtb_info.ip_is_tor_exit_node",
      "type": "boolean"
    },
    {
      "name": "impreq_rtb_info.ip",
      "type": "string"
    },
    {
      "name": "impreq_rtb_info.google_fpid",
      "type": "string"
    },
    {
      "name": "impreq_rtb_info.google_fpid_stype",
      "type": "string"
    },
    {
      "name": "user_db_info",
      "type": "string"
    },
    {
      "name": "minimum_bid_to_win",
      "type": "double"
    },
    {
      "name": "hwv",
      "type": "string"
    },
    {
      "name": "fuzzy_user_db_info",
      "type": "string"
    },
    {
      "name": "skadn_request_sourceapp",
      "type": "string"
    },
    {
      "name": "skadn_request_version",
      "type": "string"
    },
    {
      "name": "skadn_campaign",
      "type": "string"
    },
    {
      "name": "skadn_itunesitem",
      "type": "string"
    },
    {
      "name": "skadn_network",
      "type": "string"
    },
    {
      "name": "skadn_sourceapp",
      "type": "string"
    },
    {
      "name": "skadn_version",
      "type": "string"
    },
    {
      "name": "skadn_request_versions",
      "type": "array<string>",
      "isArrayPrimitive": true,
      "elementType": "string"
    },
    {
      "name": "imps",
      "type": "map"
    },
    {
      "name": "atts",
      "type": "integer"
    },
    {
      "name": "rtb_cost_usd_appier",
      "type": "double"
    },
    {
      "name": "log_types",
      "type": "array<string>",
      "isArrayPrimitive": true,
      "elementType": "string"
    },
    {
      "name": "audience_list",
      "type": "array<string>",
      "isArrayPrimitive": true,
      "elementType": "string"
    },
    {
      "name": "payment_id_chain",
      "type": "string"
    },
    {
      "name": "arms",
      "type": "array<struct>",
      "isArrayStruct": true,
      "elementFields": [
        {
          "name": "action_id",
          "type": "string"
        },
        {
          "name": "api",
          "type": "integer"
        },
        {
          "name": "postback_time",
          "type": "long"
        }
      ]
    },
    {
      "name": "arms.action_id",
      "type": "string"
    },
    {
      "name": "arms.api",
      "type": "integer"
    },
    {
      "name": "arms.postback_time",
      "type": "long"
    },
    {
      "name": "touch_level",
      "type": "integer"
    },
    {
      "name": "auction_result",
      "type": "string"
    },
    {
      "name": "losing_bids",
      "type": "array<struct>",
      "isArrayStruct": true,
      "elementFields": [
        {
          "name": "cid",
          "type": "string"
        },
        {
          "name": "price_appier",
          "type": "double"
        },
        {
          "name": "mmp_imp_tracker_location",
          "type": "string"
        },
        {
          "name": "mmp_click_tracker_location",
          "type": "string"
        },
        {
          "name": "is_ghost_ads",
          "type": "boolean"
        }
      ]
    },
    {
      "name": "losing_bids.cid",
      "type": "string"
    },
    {
      "name": "losing_bids.price_appier",
      "type": "double"
    },
    {
      "name": "losing_bids.mmp_imp_tracker_location",
      "type": "string"
    },
    {
      "name": "losing_bids.mmp_click_tracker_location",
      "type": "string"
    },
    {
      "name": "losing_bids.is_ghost_ads",
      "type": "boolean"
    },
    {
      "name": "mmp_imp_tracker_location",
      "type": "string"
    },
    {
      "name": "mmp_click_tracker_location",
      "type": "string"
    },
    {
      "name": "click_handler_version",
      "type": "integer"
    },
    {
      "name": "skadn_fidelities",
      "type": "array<integer>",
      "isArrayPrimitive": true,
      "elementType": "integer"
    },
    {
      "name": "skoverlay.video_delay",
      "type": "integer"
    },
    {
      "name": "load_rtb_info.time",
      "type": "long"
    },
    {
      "name": "load_rtb_info.ip",
      "type": "string"
    },
    {
      "name": "skadn_source_identifier",
      "type": "string"
    },
    {
      "name": "topics",
      "type": "array<struct>",
      "isArrayStruct": true,
      "elementFields": [
        {
          "name": "id",
          "type": "integer"
        },
        {
          "name": "taxonomy_version",
          "type": "string"
        },
        {
          "name": "classifier_version",
          "type": "string"
        }
      ]
    },
    {
      "name": "topics.id",
      "type": "integer"
    },
    {
      "name": "topics.taxonomy_version",
      "type": "string"
    },
    {
      "name": "topics.classifier_version",
      "type": "string"
    },
    {
      "name": "displaymanager",
      "type": "string"
    },
    {
      "name": "displaymanagerver",
      "type": "string"
    },
    {
      "name": "bcat",
      "type": "array<string>",
      "isArrayPrimitive": true,
      "elementType": "string"
    },
    {
      "name": "mmp_trackings",
      "type": "array<struct>",
      "isArrayStruct": true,
      "elementFields": [
        {
          "name": "time",
          "type": "long"
        },
        {
          "name": "ip",
          "type": "string"
        },
        {
          "name": "mmp_event",
          "type": "string"
        }
      ]
    },
    {
      "name": "mmp_trackings.time",
      "type": "long"
    },
    {
      "name": "mmp_trackings.ip",
      "type": "string"
    },
    {
      "name": "mmp_trackings.mmp_event",
      "type": "string"
    },
    {
      "name": "supply_chain.nodes",
      "type": "array<struct>",
      "isArrayStruct": true,
      "elementFields": [
        {
          "name": "asi",
          "type": "string"
        }
      ]
    },
    {
      "name": "supply_chain.nodes.asi",
      "type": "string"
    },
    {
      "name": "ad_group_prerank_info.algo",
      "type": "integer"
    },
    {
      "name": "ad_group_prerank_info.version",
      "type": "string"
    },
    {
      "name": "support_asv",
      "type": "boolean"
    },
    {
      "name": "support_dualendcard",
      "type": "boolean"
    },
    {
      "name": "support_skoverlay",
      "type": "boolean"
    },
    {
      "name": "metro_code",
      "type": "integer"
    },
    {
      "name": "asv",
      "type": "boolean"
    },
    {
      "name": "customer.coupang_lptag",
      "type": "string"
    },
    {
      "name": "_dt",
      "type": "string"
    }
  ]
};
