class UIManager {
  constructor(state, fieldMappings) {
    this.state = state;
    this.fieldMappings = fieldMappings;
    this.elements = {};
  }

  init() {
    this.cacheElements();
  }

  cacheElements() {
    this.elements = {
      selectFields: document.getElementById('selectFields'),
      whereConditions: document.getElementById('whereConditions'),
      addFieldBtn: document.getElementById('addFieldBtn'),
      addConditionBtn: document.getElementById('addConditionBtn'),
      generateBtn: document.getElementById('generateBtn'),
      copyBtn: document.getElementById('copyBtn'),
      selectHeader: document.getElementById('selectHeader'),
      tableName: document.getElementById('tableName'),
      startTime: document.getElementById('startTime'),
      endTime: document.getElementById('endTime'),
      timezone: document.getElementById('timezone'),
      queryOutput: document.getElementById('queryOutput')
    };
  }

  showLoading() {
    this.elements.selectFields.innerHTML = '<div class="loading">Loading schema fields...</div>';
  }

  clearLoading() {
    this.elements.selectFields.innerHTML = '';
  }

  formatFieldOption(field) {
    if (!field.isCustomize) {
      return `${field.name} | ${field.type}`;
    }
    return field.isAutoGenerated
      ? `${field.name} | BYTES2STR`
      : `${field.name} | Customize`;
  }

  buildFieldOptionsHtml() {
    const customizeFields = this.state.getCustomizeFields();
    const schemaFields = this.state.getSchemaFields();

    let html = '<option value="">-- Select Field --</option>';

    if (customizeFields.length > 0) {
      html += '<optgroup label="Customize Fields">';
      html += customizeFields.map(field => this.buildFieldOptionHtml(field)).join('');
      html += '</optgroup>';
    }

    html += '<optgroup label="Other"><option value="custom">custom (free input)</option></optgroup>';

    if (schemaFields.length > 0) {
      html += '<optgroup label="Schema Fields">';
      html += schemaFields.map(field =>
        `<option value="${field.name}" data-type="${field.type}">${this.formatFieldOption(field)}</option>`
      ).join('');
      html += '</optgroup>';
    }

    return html;
  }

  buildFieldOptionHtml(field) {
    const displayText = this.formatFieldOption(field);
    const mappingSql = field.isAutoGenerated && field.mapping ? field.mapping.sql : '';
    const mappingAlias = field.isAutoGenerated && field.mapping ? field.mapping.alias : '';

    return `<option value="${field.name}"
      data-is-customize="true"
      data-is-auto-generated="${field.isAutoGenerated || false}"
      data-mapping-sql="${encodeURIComponent(mappingSql)}"
      data-mapping-alias="${mappingAlias}">${displayText}</option>`;
  }

  addFieldRow() {
    const fieldId = Date.now();
    const fieldRow = document.createElement('div');
    fieldRow.className = 'field-row';
    fieldRow.dataset.fieldId = fieldId;

    fieldRow.innerHTML = `
      <select class="field-selector input-field">
        ${this.buildFieldOptionsHtml()}
      </select>
      <span class="as-label">AS</span>
      <input type="text" class="field-alias input-field" placeholder="alias" />
      <button class="btn-remove">\u00d7</button>
    `;

    this.elements.selectFields.appendChild(fieldRow);
    this.attachFieldRowListeners(fieldRow);
  }

  attachFieldRowListeners(fieldRow) {
    const selector = fieldRow.querySelector('.field-selector');
    const aliasInput = fieldRow.querySelector('.field-alias');
    const removeBtn = fieldRow.querySelector('.btn-remove');

    selector.addEventListener('change', (e) => this.handleFieldSelection(e, aliasInput));
    removeBtn.addEventListener('click', () => fieldRow.remove());
  }

  handleFieldSelection(e, aliasInput) {
    const selectedField = e.target.value;
    const selectedOption = e.target.options[e.target.selectedIndex];
    const isCustomize = selectedOption.dataset.isCustomize === 'true';
    const isAutoGenerated = selectedOption.dataset.isAutoGenerated === 'true';

    if (!selectedField || selectedField === 'custom') {
      aliasInput.disabled = false;
      aliasInput.value = '';
      return;
    }

    if (!isCustomize) {
      const baseName = selectedField.includes('.') ? selectedField.split('.').pop() : selectedField;
      aliasInput.value = baseName;
      aliasInput.disabled = false;
      return;
    }

    if (isAutoGenerated) {
      aliasInput.value = selectedOption.dataset.mappingAlias || selectedField;
      aliasInput.disabled = true;
      return;
    }

    const mapping = this.fieldMappings[selectedField];
    if (mapping) {
      aliasInput.value = mapping.alias;
      aliasInput.disabled = true;
    }
  }

  addConditionRow() {
    const conditionId = Date.now();
    const conditionRow = document.createElement('div');
    conditionRow.className = 'condition-row';
    conditionRow.dataset.conditionId = conditionId;

    conditionRow.innerHTML = `
      <select class="condition-type input-field">
        <option value="">-- Select Condition --</option>
        <option value="bid_win">Win Bid (RTB)</option>
        <option value="bid_non_win">Non-Win Bid (RTB)</option>
        <option value="custom">Custom</option>
      </select>
      <input type="text" class="condition-value input-field" placeholder="Custom SQL condition" style="display:none;" />
      <button class="btn-remove">\u00d7</button>
    `;

    this.elements.whereConditions.appendChild(conditionRow);
    this.attachConditionRowListeners(conditionRow);
  }

  attachConditionRowListeners(conditionRow) {
    const typeSelector = conditionRow.querySelector('.condition-type');
    const valueInput = conditionRow.querySelector('.condition-value');
    const removeBtn = conditionRow.querySelector('.btn-remove');

    typeSelector.addEventListener('change', (e) => {
      valueInput.style.display = e.target.value === 'custom' ? 'inline-block' : 'none';
    });

    removeBtn.addEventListener('click', () => conditionRow.remove());
  }

  handleQueryTypeChange(isDistinct) {
    this.elements.addFieldBtn.style.display = isDistinct ? 'none' : '';
    this.elements.selectHeader.textContent = isDistinct ? 'SELECT DISTINCT' : 'SELECT';

    if (!isDistinct) return;

    const fieldRows = this.elements.selectFields.querySelectorAll('.field-row');
    fieldRows.forEach((row, index) => {
      if (index > 0) row.remove();
    });
  }

  getFieldRowsData() {
    const fieldRows = document.querySelectorAll('.field-row');
    return Array.from(fieldRows).map(row => {
      const selector = row.querySelector('.field-selector');
      const selectedOption = selector.options[selector.selectedIndex];
      return {
        fieldType: selector.value,
        isCustomize: selectedOption?.dataset?.isCustomize === 'true',
        isAutoGenerated: selectedOption?.dataset?.isAutoGenerated === 'true',
        mappingSql: selectedOption?.dataset?.mappingSql || '',
        mappingAlias: selectedOption?.dataset?.mappingAlias || '',
        alias: row.querySelector('.field-alias').value
      };
    });
  }

  getConditionRowsData() {
    const conditionRows = document.querySelectorAll('.condition-row');
    return Array.from(conditionRows).map(row => ({
      conditionType: row.querySelector('.condition-type').value,
      customValue: row.querySelector('.condition-value').value
    }));
  }

  getFromClauseData() {
    return {
      tableName: this.elements.tableName.value || 'imp_join_all2',
      startTime: this.elements.startTime.value,
      endTime: this.elements.endTime.value,
      timezone: this.elements.timezone.value
    };
  }

  setQueryOutput(query) {
    this.elements.queryOutput.value = query;
  }

  async copyToClipboard() {
    const text = this.elements.queryOutput.value;

    try {
      await navigator.clipboard.writeText(text);
      this.showCopyFeedback();
    } catch (err) {
      this.elements.queryOutput.select();
      document.execCommand('copy');
      this.showCopyFeedback();
    }
  }

  showCopyFeedback() {
    const originalText = this.elements.copyBtn.textContent;
    this.elements.copyBtn.textContent = 'Copied!';
    setTimeout(() => {
      this.elements.copyBtn.textContent = originalText;
    }, 2000);
  }
}